# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5gpRukAAWTk0JptwX1dq40Ze89NShil
"""

import streamlit as st
import pickle
import pandas as pd
import re
import nltk
import sqlite3
import plotly.express as px
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import cosine_similarity
import PyPDF2
from datetime import datetime

nltk.download('stopwords', quiet=True)

# ---------------- STYLE ---------------- #
st.set_page_config(page_title="HireScope Intelligence", layout="wide")

st.markdown("""
<style>

/* spacing */
.block-container {
    padding-top: 2rem;
}

/* cards */
.card {
    background-color: #1c1f26;
    padding: 15px;
    border-radius: 12px;
    margin-bottom: 15px;
    box-shadow: 0 4px 10px rgba(0,0,0,0.3);
}

/* headings */
h1, h2, h3 {
    color: #00ADB5;
}

/* buttons */
.stButton>button {
    border-radius: 10px;
    background-color: #00ADB5;
    color: white;
}

/* score */
.score {
    font-weight: bold;
    color: #00ADB5;
}

</style>
""", unsafe_allow_html=True)

# ---------------- DATABASE ---------------- #
conn = sqlite3.connect("users.db", check_same_thread=False)
c = conn.cursor()
c.execute("CREATE TABLE IF NOT EXISTS users(email TEXT PRIMARY KEY, password TEXT)")

# ---------------- SESSION ---------------- #
if "user" not in st.session_state:
    st.session_state.user = None
if "resume" not in st.session_state:
    st.session_state.resume = ""
if "predicted_role" not in st.session_state:
    st.session_state.predicted_role = ""
if "history" not in st.session_state:
    st.session_state.history = []

# ---------------- LOAD ---------------- #
@st.cache_resource
def load():
    model = pickle.load(open("model.pkl", "rb"))
    tfidf = pickle.load(open("tfidf.pkl", "rb"))
    le = pickle.load(open("label_encoder.pkl", "rb"))
    job_df = pd.read_csv("job_dataset_final.csv")
    return model, tfidf, le, job_df

model, tfidf, le, job_df = load()
stop_words = set(stopwords.words('english'))

APP_NAME = "HireScope Intelligence"
def show_header():
    st.markdown("""
    <h1 style="text-align:center; margin-bottom:0;">
     HireScope Intelligence
    </h1>

    <p style="text-align:center; font-size:13px; font-style:italic; color:gray; margin-top:5px;">
     AI-powered Resume Screening • Job Prediction • Career Recommendation System
    </p>

    <hr>
    """, unsafe_allow_html=True)

# ---------------- FUNCTIONS ---------------- #
def get_name(email):
    return email.split("@")[0].capitalize()

def clean(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    return " ".join([w for w in text.split() if w not in stop_words])

def extract(file):
    reader = PyPDF2.PdfReader(file)
    return "".join([p.extract_text() or "" for p in reader.pages])

def predict_role(text):
    vec = tfidf.transform([clean(text)])
    pred = model.predict(vec)
    return le.inverse_transform(pred)[0]

def recommend(text, top_n):
    vec = tfidf.transform([clean(text)])
    job_vec = tfidf.transform(job_df['Text'])
    sim = cosine_similarity(vec, job_vec)[0]

    df = job_df.copy()
    df["Score"] = 80 + (sim * 20)
    df = df.sort_values(by="Score", ascending=False)
    df = df.drop_duplicates(subset="Job_Role")
    return df.head(top_n)

def add_history(file_name):
    st.session_state.history.append({
        "time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "file": file_name
    })

# ---------------- ROLE SKILLS ---------------- #
role_skills = {
    "data science": ["python","machine learning","nlp","statistics","pandas"],
    "hr": ["recruitment","communication","employee relations"],
    "advocate": ["legal research","litigation","drafting"],
    "arts": ["creativity","design","visualization"],
    "web designing": ["html","css","javascript","ui","ux"],
    "mechanical engineer": ["cad","solidworks","manufacturing"],
    "sales": ["communication","negotiation","crm"],
    "health and fitness": ["nutrition","fitness training","wellness"],
    "civil engineer": ["autocad","construction","planning"],
    "java developer": ["java","spring","api","backend"],
    "business analyst": ["sql","excel","requirement analysis"],
    "sap developer": ["sap","abap","erp"],
    "automation testing": ["selenium","testng","automation"],
    "electrical engineering": ["circuits","power systems","matlab"],
    "operations manager": ["management","planning","logistics"],
    "python developer": ["python","django","flask","api"],
    "devops engineer": ["docker","kubernetes","ci cd","linux"],
    "network security engineer": ["cybersecurity","networking","firewalls"],
    "pmo": ["project management","planning","coordination"],
    "database": ["sql","mysql","oracle"],
    "hadoop": ["hadoop","big data","spark"],
    "etl developer": ["etl","data pipeline","ssis"],
    "dotnet developer": [".net","c#","asp.net"],
    "blockchain": ["blockchain","smart contracts","solidity"],
    "testing": ["manual testing","automation","bug tracking"]
}
mnc_roles = {
    "data science": [
        "Google → https://careers.google.com",
        "Microsoft → https://www.microsoft.com/en-us/careers",
        "Amazon → https://www.amazon.jobs",
        "Meta → https://www.metacareers.com",
        "TCS → https://www.tcs.com/careers"
    ],

    "python developer": [
        "Amazon → https://www.amazon.jobs",
        "Google → https://careers.google.com",
        "Microsoft → https://www.microsoft.com/en-us/careers",
        "Infosys → https://www.infosys.com/careers",
        "Accenture → https://www.accenture.com/careers"
    ],

    "java developer": [
        "Oracle → https://www.oracle.com/careers",
        "IBM → https://www.ibm.com/careers",
        "Google → https://careers.google.com",
        "Microsoft → https://www.microsoft.com/en-us/careers",
        "Amazon → https://www.amazon.jobs"
    ],

    "devops engineer": [
        "AWS → https://www.amazon.jobs",
        "Microsoft → https://www.microsoft.com/en-us/careers",
        "RedHat → https://www.redhat.com/en/jobs",
        "IBM → https://www.ibm.com/careers",
        "Google → https://careers.google.com"
    ],

    "business analyst": [
        "Accenture → https://www.accenture.com/careers",
        "Deloitte → https://www2.deloitte.com/careers",
        "PwC → https://www.pwc.com/careers",
        "TCS → https://www.tcs.com/careers",
        "Infosys → https://www.infosys.com/careers"
    ],

    "default": [
        "TCS → https://www.tcs.com/careers",
        "Infosys → https://www.infosys.com/careers",
        "Accenture → https://www.accenture.com/careers",
        "Google → https://careers.google.com",
        "Amazon → https://www.amazon.jobs"
    ]
}
# ---------------- LOGIN ---------------- #
def login():
    email = st.text_input("Email", key="login_email")
    password = st.text_input("Password", type="password", key="login_pass")

    if st.button("Login"):
        user = c.execute("SELECT * FROM users WHERE email=? AND password=?", (email, password)).fetchone()
        if user:
            st.session_state.user = email
            st.rerun()
        else:
            st.error("Invalid credentials")

def register():
    email = st.text_input("Email", key="reg_email")
    password = st.text_input("Password", type="password", key="reg_pass")

    if st.button("Register"):
        c.execute("INSERT INTO users VALUES (?,?)", (email, password))
        conn.commit()
        st.success("Account created")

def reset():
    email = st.text_input("Email", key="reset_email")
    password = st.text_input("New Password", type="password", key="reset_pass")

    if st.button("Reset"):
        c.execute("UPDATE users SET password=? WHERE email=?", (password, email))
        conn.commit()
        st.success("Updated")

# ---------------- AUTH ---------------- #
if not st.session_state.user:
    st.title("HireScope Intelligence Login")
    tab1, tab2, tab3 = st.tabs(["Login", "Register", "Reset"])
    with tab1: login()
    with tab2: register()
    with tab3: reset()


# ---------------- MAIN ---------------- #

else:
    show_header()
    st.sidebar.title("🔍 Navigation")

    page = st.sidebar.radio("", [
        "Home",
        "Job Recommendations",
        "Skill Analysis",
        "Learning Path",
        "Top MNC Careers",
        "Job Portals",
        "Resume vs JD Match",
        "Select Job Role"
    ])

    st.sidebar.markdown("---")

    st.sidebar.subheader("History")
    for h in st.session_state.history[-5:]:
        st.sidebar.write(f"{h['time']} - {h['file']}")

    if st.sidebar.button("🔄 Refresh"):
        st.session_state.resume = ""
        st.session_state.predicted_role = ""

    if st.sidebar.button("🚪 Logout"):
        st.session_state.user = None
        st.rerun()



    # ---------------- HOME ---------------- #

    if page == "Home":

        st.markdown("""
    ### Upload your resume below to get AI insights
    """, unsafe_allow_html=True)

        file = st.file_uploader("Upload Resume", type=["pdf"])
        text = st.text_area("Or paste resume")

        if file:
            st.session_state.resume = extract(file)
            add_history(file.name)
        elif text:
            st.session_state.resume = text

        if st.session_state.resume:
            role = predict_role(st.session_state.resume)
            st.session_state.predicted_role = role
            st.success(f"🎯 Predicted Role: {role}")

    # ---------------- JOB ---------------- #
    elif page == "Job Recommendations":

        if st.session_state.resume:

            top_n = st.slider("Top Jobs", 1, 10, 5)

            if st.button("Get Recommendations"):

                results = recommend(st.session_state.resume, top_n)

                names, scores = [], []

                for _, row in results.iterrows():

                    st.markdown(f"""
                    <div class="card">
                        <h4>{row['Job_Role']}</h4>
                        <p>{row['Text'][:200]}...</p>
                        <p class="score">Match Score: {int(row['Score'])}%</p>
                    </div>
                    """, unsafe_allow_html=True)

                    names.append(row['Job_Role'])
                    scores.append(row['Score'])

                df_plot = pd.DataFrame({"Role": names, "Score": scores})

                fig = px.bar(df_plot, x="Role", y="Score", color="Score", text="Score")
                fig.update_traces(textposition='outside')
                st.plotly_chart(fig, use_container_width=True)

    # ---------------- SKILL ---------------- #
    elif page == "Skill Analysis":

        role = st.session_state.predicted_role.lower().strip()

        if role in role_skills:
            skills = role_skills[role]

            found = [s for s in skills if s in st.session_state.resume.lower()]
            missing = list(set(skills) - set(found))

            st.success("Matching Skills")
            st.write(found)

            st.error("Missing Skills")
            st.write(missing)

    # ---------------- LEARNING ---------------- #
    elif page == "Learning Path":

        role = st.session_state.predicted_role.lower().strip()

        if role in role_skills:
            skills = role_skills[role]
            missing = [s for s in skills if s not in st.session_state.resume.lower()]

            st.subheader("📚 Learning Plan")

            if missing:
                for i, s in enumerate(missing, 1):
                    st.markdown(f'<div class="card">{i}. Learn {s}</div>', unsafe_allow_html=True)
            else:
                st.success("You already have all required skills!")

    # ---------------- MNC ---------------- #
    elif page == "Top MNC Careers":

        role = st.session_state.predicted_role.lower().strip()

        st.subheader(f"🏢 Top MNCs for: {role}")

        links = mnc_roles.get(role, mnc_roles["default"])

        for company in links:
            st.markdown(f"🔗 {company}")

    # ---------------- PORTALS ---------------- #
    elif page == "Job Portals":
        st.markdown("🔗 https://linkedin.com/jobs")
        st.markdown("🔗 https://indeed.com")
        st.markdown("🔗 https://naukri.com")

    # ---------------- MATCH ---------------- #
    elif page == "Resume vs JD Match":

        jd = st.text_area("Paste Job Description")

        if st.button("Check Match"):

            if st.session_state.resume and jd:

                resume_clean = clean(st.session_state.resume)
                jd_clean = clean(jd)

                v1 = tfidf.transform([resume_clean])
                v2 = tfidf.transform([jd_clean])

                score = int(cosine_similarity(v1, v2)[0][0] * 100)

                st.success(f"🎯 Match Score: {score}%")

                resume_words = set(resume_clean.split())
                jd_words = set(jd_clean.split())

                common = resume_words.intersection(jd_words)
                missing = jd_words - resume_words

                st.markdown("### ✅ Matching Keywords")
                st.write(list(common)[:20])

                st.markdown("### ❌ Missing Keywords")
                st.write(list(missing)[:20])

            else:
                st.warning("Upload resume & paste JD")

    # ---------------- ROLE FILTER ---------------- #
    elif page == "Select Job Role":

        selected_role = st.selectbox("Select Role", list(role_skills.keys()))

        st.subheader("Required Skills")
        st.write(role_skills[selected_role])