# -*- coding: utf-8 -*-
"""HireScope Intelligence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBfb-9ffu28i1iQiWo1zT3TCZJbfKGzi

#HireScope Intelligence
##AI-Based Resume Screening, Job Role Prediction & Job Recommendation System using NLP and Machine Learning

STEP 1: Import Libraries
"""

import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import plotly.express as px

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics.pairwise import cosine_similarity

# ML Models (Auto ML style)
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

nltk.download('stopwords', quiet=True)

"""STEP 2: Load Datasets"""

resume_df = pd.read_csv("/content/UpdatedResumeDataSet.csv")
job_df = pd.read_csv("/content/advanced_job_dataset.csv")

resume_df.head()

job_df.head()

job_df["Job_Role"].unique()

"""STEP 3: Rename Columns"""

resume_df = resume_df.rename(columns={"Category": "Job_Role", "Resume": "Text"})
job_df = job_df.rename(columns={"Description": "Text"})

"""STEP 4: Data Cleaning"""

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = " ".join([word for word in text.split() if word not in stop_words])
    return text

resume_df['Clean_Text'] = resume_df['Text'].apply(clean_text)
job_df['Clean_Text'] = job_df['Text'].apply(clean_text)

"""STEP 5: EDA (Interactive Plot)"""

role_counts = resume_df['Job_Role'].value_counts().reset_index()
role_counts.columns = ['Role', 'Count']

fig = px.bar(role_counts, x='Role', y='Count', title="Job Role Distribution")
fig.show()

"""STEP 6: TF-IDF Vectorization"""

tfidf = TfidfVectorizer(max_features=3000)

X = tfidf.fit_transform(resume_df['Clean_Text'])
y = resume_df['Job_Role']

"""STEP 7: Encode Labels"""

le = LabelEncoder()
y_encoded = le.fit_transform(y)

"""STEP 8: Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

"""STEP 9: Auto ML (Multiple Models)"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": MultinomialNB(),
    "SVM": LinearSVC(),
    "Random Forest": RandomForestClassifier()
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    results[name] = acc
    print(f"{name}: {acc}")

"""STEP 10: Compare Models (Interactive)"""

results_df = pd.DataFrame(list(results.items()), columns=['Model', 'Accuracy'])

fig = px.bar(results_df, x='Model', y='Accuracy', title="Model Comparison")
fig.show()

"""STEP 11: Choose Best Model"""

best_model = LogisticRegression(max_iter=1000)
best_model.fit(X_train, y_train)

"""STEP 12: Evaluation Metrics"""

y_pred = best_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.imshow(cm)
plt.title("Confusion Matrix")
plt.colorbar()
plt.show()

"""STEP 13: Job Recommendation System"""

job_vectors = tfidf.transform(job_df['Clean_Text'])

def recommend_jobs(resume_text):
    clean = clean_text(resume_text)
    vector = tfidf.transform([clean])

    similarity = cosine_similarity(vector, job_vectors)
    top_indices = similarity[0].argsort()[-3:][::-1]

    return job_df.iloc[top_indices][['Job_Role', 'Text']]

"""STEP 14: Prediction Function"""

def predict_role(resume_text):
    clean = clean_text(resume_text)
    vector = tfidf.transform([clean])

    pred = best_model.predict(vector)
    return le.inverse_transform(pred)[0]

"""STEP 15: Final Testing"""

sample_resume = resume_df['Text'][0]

print("Predicted Role:", predict_role(sample_resume))
print("\nRecommended Jobs:")
print(recommend_jobs(sample_resume))

"""STEP 16: Final Interactive Demo Plot"""

# Show similarity scores for top matches
def show_similarity(resume_text):
    clean = clean_text(resume_text)
    vector = tfidf.transform([clean])

    similarity = cosine_similarity(vector, job_vectors)[0]

    df_sim = pd.DataFrame({
        'Job Role': job_df['Job_Role'],
        'Score': similarity
    }).sort_values(by='Score', ascending=False).head(10)

    fig = px.bar(df_sim, x='Job Role', y='Score', title="Top Matching Jobs")
    fig.show()

show_similarity(sample_resume)

"""#Import Pickle files :"""

import pickle

# Save model
pickle.dump(best_model, open("model.pkl", "wb"))

# Save TF-IDF
pickle.dump(tfidf, open("tfidf.pkl", "wb"))

# Save Label Encoder
pickle.dump(le, open("label_encoder.pkl", "wb"))

# Save job dataset
job_df.to_csv("job_dataset_final.csv", index=False)

